# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin_open.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_admin_open(object):
    def setupUi(self, admin_open):
        admin_open.setObjectName("admin_open")
        admin_open.resize(953, 592)
        admin_open.setMinimumSize(QtCore.QSize(953, 592))
        admin_open.setMaximumSize(QtCore.QSize(953, 592))
        self.label = QtWidgets.QLabel(admin_open)
        self.label.setGeometry(QtCore.QRect(370, 10, 251, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayoutWidget = QtWidgets.QWidget(admin_open)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(170, 100, 271, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sys_fn = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_fn.setFont(font)
        self.sys_fn.setText("")
        self.sys_fn.setMaxLength(50)
        self.sys_fn.setObjectName("sys_fn")
        self.verticalLayout.addWidget(self.sys_fn)
        self.sys_mn = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_mn.setFont(font)
        self.sys_mn.setText("")
        self.sys_mn.setMaxLength(50)
        self.sys_mn.setObjectName("sys_mn")
        self.verticalLayout.addWidget(self.sys_mn)
        self.sys_ln = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_ln.setFont(font)
        self.sys_ln.setText("")
        self.sys_ln.setMaxLength(50)
        self.sys_ln.setObjectName("sys_ln")
        self.verticalLayout.addWidget(self.sys_ln)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(admin_open)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 100, 125, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(admin_open)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(510, 100, 131, 121))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(admin_open)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(650, 100, 271, 121))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.sys_age = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_age.setFont(font)
        self.sys_age.setText("")
        self.sys_age.setMaxLength(3)
        self.sys_age.setObjectName("sys_age")
        self.verticalLayout_4.addWidget(self.sys_age)
        self.sys_contact = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_contact.setFont(font)
        self.sys_contact.setText("")
        self.sys_contact.setMaxLength(11)
        self.sys_contact.setObjectName("sys_contact")
        self.verticalLayout_4.addWidget(self.sys_contact)
        self.sys_email = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_email.setFont(font)
        self.sys_email.setText("")
        self.sys_email.setMaxLength(50)
        self.sys_email.setObjectName("sys_email")
        self.verticalLayout_4.addWidget(self.sys_email)
        self.label_8 = QtWidgets.QLabel(admin_open)
        self.label_8.setGeometry(QtCore.QRect(30, 250, 123, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.sys_add = QtWidgets.QLineEdit(admin_open)
        self.sys_add.setGeometry(QtCore.QRect(130, 250, 791, 27))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_add.setFont(font)
        self.sys_add.setText("")
        self.sys_add.setObjectName("sys_add")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(admin_open)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(30, 310, 165, 121))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_5.addWidget(self.label_11)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(admin_open)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(210, 310, 271, 121))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sys_cn = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_cn.setFont(font)
        self.sys_cn.setInputMask("")
        self.sys_cn.setText("")
        self.sys_cn.setMaxLength(16)
        self.sys_cn.setObjectName("sys_cn")
        self.verticalLayout_6.addWidget(self.sys_cn)
        self.sys_an = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_an.setFont(font)
        self.sys_an.setText("")
        self.sys_an.setMaxLength(12)
        self.sys_an.setObjectName("sys_an")
        self.verticalLayout_6.addWidget(self.sys_an)
        self.sys_pin = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_pin.setFont(font)
        self.sys_pin.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.sys_pin.setText("")
        self.sys_pin.setMaxLength(6)
        self.sys_pin.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sys_pin.setObjectName("sys_pin")
        self.verticalLayout_6.addWidget(self.sys_pin)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(admin_open)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(610, 330, 188, 80))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.sys_checking = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_checking.setFont(font)
        self.sys_checking.setObjectName("sys_checking")
        self.verticalLayout_8.addWidget(self.sys_checking)
        self.sys_savings = QtWidgets.QRadioButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sys_savings.setFont(font)
        self.sys_savings.setObjectName("sys_savings")
        self.verticalLayout_8.addWidget(self.sys_savings)
        self.horizontalLayoutWidget = QtWidgets.QWidget(admin_open)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 460, 351, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sys_create = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sys_create.setFont(font)
        self.sys_create.setObjectName("sys_create")
        self.horizontalLayout.addWidget(self.sys_create)
        self.sys_cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sys_cancel.setFont(font)
        self.sys_cancel.setObjectName("sys_cancel")
        self.horizontalLayout.addWidget(self.sys_cancel)

        self.retranslateUi(admin_open)
        QtCore.QMetaObject.connectSlotsByName(admin_open)

    def retranslateUi(self, admin_open):
        _translate = QtCore.QCoreApplication.translate
        admin_open.setWindowTitle(_translate("admin_open", "Open Account"))
        self.label.setText(_translate("admin_open", "OPEN ACCOUNT"))
        self.label_2.setText(_translate("admin_open", "FIRST NAME:"))
        self.label_4.setText(_translate("admin_open", "MIDDLE NAME:"))
        self.label_3.setText(_translate("admin_open", "LAST NAME:"))
        self.label_5.setText(_translate("admin_open", "AGE:"))
        self.label_6.setText(_translate("admin_open", "CONTACT #:"))
        self.label_7.setText(_translate("admin_open", "EMAIL:"))
        self.label_8.setText(_translate("admin_open", "ADDRESS:"))
        self.label_9.setText(_translate("admin_open", "CARD NUMBER:"))
        self.label_10.setText(_translate("admin_open", "ACCOUNT NUMBER:"))
        self.label_11.setText(_translate("admin_open", "PIN NUMBER:"))
        self.sys_checking.setText(_translate("admin_open", "CHECKING ACCOUNT"))
        self.sys_savings.setText(_translate("admin_open", "SAVINGS ACCOUNT"))
        self.sys_create.setText(_translate("admin_open", "CREATE"))
        self.sys_cancel.setText(_translate("admin_open", "CANCEL"))



